//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyForgeClient.MuscleService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Muscle", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Muscle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MuscleService.MuscleWebServiceSoap")]
    public interface MuscleWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        BodyForgeClient.MuscleService.getByIdResponse getById(BodyForgeClient.MuscleService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.MuscleService.getByIdResponse> getByIdAsync(BodyForgeClient.MuscleService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        BodyForgeClient.MuscleService.getAllResponse getAll(BodyForgeClient.MuscleService.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.MuscleService.getAllResponse> getAllAsync(BodyForgeClient.MuscleService.getAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getById", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.MuscleService.getByIdRequestBody Body;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(BodyForgeClient.MuscleService.getByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public getByIdRequestBody() {
        }
        
        public getByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.MuscleService.getByIdResponseBody Body;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(BodyForgeClient.MuscleService.getByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.MuscleService.Muscle getByIdResult;
        
        public getByIdResponseBody() {
        }
        
        public getByIdResponseBody(BodyForgeClient.MuscleService.Muscle getByIdResult) {
            this.getByIdResult = getByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.MuscleService.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(BodyForgeClient.MuscleService.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRequestBody {
        
        public getAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.MuscleService.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(BodyForgeClient.MuscleService.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.MuscleService.Muscle[] getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(BodyForgeClient.MuscleService.Muscle[] getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MuscleWebServiceSoapChannel : BodyForgeClient.MuscleService.MuscleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MuscleWebServiceSoapClient : System.ServiceModel.ClientBase<BodyForgeClient.MuscleService.MuscleWebServiceSoap>, BodyForgeClient.MuscleService.MuscleWebServiceSoap {
        
        public MuscleWebServiceSoapClient() {
        }
        
        public MuscleWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MuscleWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MuscleWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MuscleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.MuscleService.getByIdResponse BodyForgeClient.MuscleService.MuscleWebServiceSoap.getById(BodyForgeClient.MuscleService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public BodyForgeClient.MuscleService.Muscle getById(long id) {
            BodyForgeClient.MuscleService.getByIdRequest inValue = new BodyForgeClient.MuscleService.getByIdRequest();
            inValue.Body = new BodyForgeClient.MuscleService.getByIdRequestBody();
            inValue.Body.id = id;
            BodyForgeClient.MuscleService.getByIdResponse retVal = ((BodyForgeClient.MuscleService.MuscleWebServiceSoap)(this)).getById(inValue);
            return retVal.Body.getByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.MuscleService.getByIdResponse> BodyForgeClient.MuscleService.MuscleWebServiceSoap.getByIdAsync(BodyForgeClient.MuscleService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.MuscleService.getByIdResponse> getByIdAsync(long id) {
            BodyForgeClient.MuscleService.getByIdRequest inValue = new BodyForgeClient.MuscleService.getByIdRequest();
            inValue.Body = new BodyForgeClient.MuscleService.getByIdRequestBody();
            inValue.Body.id = id;
            return ((BodyForgeClient.MuscleService.MuscleWebServiceSoap)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.MuscleService.getAllResponse BodyForgeClient.MuscleService.MuscleWebServiceSoap.getAll(BodyForgeClient.MuscleService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public BodyForgeClient.MuscleService.Muscle[] getAll() {
            BodyForgeClient.MuscleService.getAllRequest inValue = new BodyForgeClient.MuscleService.getAllRequest();
            inValue.Body = new BodyForgeClient.MuscleService.getAllRequestBody();
            BodyForgeClient.MuscleService.getAllResponse retVal = ((BodyForgeClient.MuscleService.MuscleWebServiceSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.MuscleService.getAllResponse> BodyForgeClient.MuscleService.MuscleWebServiceSoap.getAllAsync(BodyForgeClient.MuscleService.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.MuscleService.getAllResponse> getAllAsync() {
            BodyForgeClient.MuscleService.getAllRequest inValue = new BodyForgeClient.MuscleService.getAllRequest();
            inValue.Body = new BodyForgeClient.MuscleService.getAllRequestBody();
            return ((BodyForgeClient.MuscleService.MuscleWebServiceSoap)(this)).getAllAsync(inValue);
        }
    }
}
