//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyForgeClient.WorkoutService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Workout", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Workout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private System.DateTime workout_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string durationField;
        
        private long id_userField;
        
        private bool is_templateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime workout_date {
            get {
                return this.workout_dateField;
            }
            set {
                if ((this.workout_dateField.Equals(value) != true)) {
                    this.workout_dateField = value;
                    this.RaisePropertyChanged("workout_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                if ((object.ReferenceEquals(this.durationField, value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool is_template {
            get {
                return this.is_templateField;
            }
            set {
                if ((this.is_templateField.Equals(value) != true)) {
                    this.is_templateField = value;
                    this.RaisePropertyChanged("is_template");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkoutService.WorkoutWebServiceSoap")]
    public interface WorkoutWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        BodyForgeClient.WorkoutService.getByIdResponse getById(BodyForgeClient.WorkoutService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getByIdResponse> getByIdAsync(BodyForgeClient.WorkoutService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since element name getByUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getByUserId", ReplyAction="*")]
        BodyForgeClient.WorkoutService.getByUserIdResponse getByUserId(BodyForgeClient.WorkoutService.getByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getByUserIdResponse> getByUserIdAsync(BodyForgeClient.WorkoutService.getByUserIdRequest request);
        
        // CODEGEN: Generating message contract since element name getTemplatesByUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTemplatesByUserId", ReplyAction="*")]
        BodyForgeClient.WorkoutService.getTemplatesByUserIdResponse getTemplatesByUserId(BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTemplatesByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getTemplatesByUserIdResponse> getTemplatesByUserIdAsync(BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest request);
        
        // CODEGEN: Generating message contract since element name workout from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkout", ReplyAction="*")]
        BodyForgeClient.WorkoutService.addWorkoutResponse addWorkout(BodyForgeClient.WorkoutService.addWorkoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkout", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.addWorkoutResponse> addWorkoutAsync(BodyForgeClient.WorkoutService.addWorkoutRequest request);
        
        // CODEGEN: Generating message contract since element name deleteWorkoutResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkout", ReplyAction="*")]
        BodyForgeClient.WorkoutService.deleteWorkoutResponse deleteWorkout(BodyForgeClient.WorkoutService.deleteWorkoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkout", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.deleteWorkoutResponse> deleteWorkoutAsync(BodyForgeClient.WorkoutService.deleteWorkoutRequest request);
        
        // CODEGEN: Generating message contract since element name workout from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateWorkout", ReplyAction="*")]
        BodyForgeClient.WorkoutService.updateWorkoutResponse updateWorkout(BodyForgeClient.WorkoutService.updateWorkoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateWorkout", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.updateWorkoutResponse> updateWorkoutAsync(BodyForgeClient.WorkoutService.updateWorkoutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getById", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.getByIdRequestBody Body;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(BodyForgeClient.WorkoutService.getByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public getByIdRequestBody() {
        }
        
        public getByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.getByIdResponseBody Body;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(BodyForgeClient.WorkoutService.getByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.WorkoutService.Workout getByIdResult;
        
        public getByIdResponseBody() {
        }
        
        public getByIdResponseBody(BodyForgeClient.WorkoutService.Workout getByIdResult) {
            this.getByIdResult = getByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByUserId", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.getByUserIdRequestBody Body;
        
        public getByUserIdRequest() {
        }
        
        public getByUserIdRequest(BodyForgeClient.WorkoutService.getByUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long userId;
        
        public getByUserIdRequestBody() {
        }
        
        public getByUserIdRequestBody(long userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.getByUserIdResponseBody Body;
        
        public getByUserIdResponse() {
        }
        
        public getByUserIdResponse(BodyForgeClient.WorkoutService.getByUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.WorkoutService.Workout[] getByUserIdResult;
        
        public getByUserIdResponseBody() {
        }
        
        public getByUserIdResponseBody(BodyForgeClient.WorkoutService.Workout[] getByUserIdResult) {
            this.getByUserIdResult = getByUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTemplatesByUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTemplatesByUserId", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.getTemplatesByUserIdRequestBody Body;
        
        public getTemplatesByUserIdRequest() {
        }
        
        public getTemplatesByUserIdRequest(BodyForgeClient.WorkoutService.getTemplatesByUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTemplatesByUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long userId;
        
        public getTemplatesByUserIdRequestBody() {
        }
        
        public getTemplatesByUserIdRequestBody(long userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTemplatesByUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTemplatesByUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.getTemplatesByUserIdResponseBody Body;
        
        public getTemplatesByUserIdResponse() {
        }
        
        public getTemplatesByUserIdResponse(BodyForgeClient.WorkoutService.getTemplatesByUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTemplatesByUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.WorkoutService.Workout[] getTemplatesByUserIdResult;
        
        public getTemplatesByUserIdResponseBody() {
        }
        
        public getTemplatesByUserIdResponseBody(BodyForgeClient.WorkoutService.Workout[] getTemplatesByUserIdResult) {
            this.getTemplatesByUserIdResult = getTemplatesByUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkout", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.addWorkoutRequestBody Body;
        
        public addWorkoutRequest() {
        }
        
        public addWorkoutRequest(BodyForgeClient.WorkoutService.addWorkoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWorkoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.WorkoutService.Workout workout;
        
        public addWorkoutRequestBody() {
        }
        
        public addWorkoutRequestBody(BodyForgeClient.WorkoutService.Workout workout) {
            this.workout = workout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.addWorkoutResponseBody Body;
        
        public addWorkoutResponse() {
        }
        
        public addWorkoutResponse(BodyForgeClient.WorkoutService.addWorkoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWorkoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addWorkoutResult;
        
        public addWorkoutResponseBody() {
        }
        
        public addWorkoutResponseBody(string addWorkoutResult) {
            this.addWorkoutResult = addWorkoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkout", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.deleteWorkoutRequestBody Body;
        
        public deleteWorkoutRequest() {
        }
        
        public deleteWorkoutRequest(BodyForgeClient.WorkoutService.deleteWorkoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public deleteWorkoutRequestBody() {
        }
        
        public deleteWorkoutRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.deleteWorkoutResponseBody Body;
        
        public deleteWorkoutResponse() {
        }
        
        public deleteWorkoutResponse(BodyForgeClient.WorkoutService.deleteWorkoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteWorkoutResult;
        
        public deleteWorkoutResponseBody() {
        }
        
        public deleteWorkoutResponseBody(string deleteWorkoutResult) {
            this.deleteWorkoutResult = deleteWorkoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateWorkoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateWorkout", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.updateWorkoutRequestBody Body;
        
        public updateWorkoutRequest() {
        }
        
        public updateWorkoutRequest(BodyForgeClient.WorkoutService.updateWorkoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateWorkoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.WorkoutService.Workout workout;
        
        public updateWorkoutRequestBody() {
        }
        
        public updateWorkoutRequestBody(BodyForgeClient.WorkoutService.Workout workout) {
            this.workout = workout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateWorkoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateWorkoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.WorkoutService.updateWorkoutResponseBody Body;
        
        public updateWorkoutResponse() {
        }
        
        public updateWorkoutResponse(BodyForgeClient.WorkoutService.updateWorkoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateWorkoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateWorkoutResult;
        
        public updateWorkoutResponseBody() {
        }
        
        public updateWorkoutResponseBody(string updateWorkoutResult) {
            this.updateWorkoutResult = updateWorkoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkoutWebServiceSoapChannel : BodyForgeClient.WorkoutService.WorkoutWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkoutWebServiceSoapClient : System.ServiceModel.ClientBase<BodyForgeClient.WorkoutService.WorkoutWebServiceSoap>, BodyForgeClient.WorkoutService.WorkoutWebServiceSoap {
        
        public WorkoutWebServiceSoapClient() {
        }
        
        public WorkoutWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkoutWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkoutWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkoutWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.WorkoutService.getByIdResponse BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.getById(BodyForgeClient.WorkoutService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public BodyForgeClient.WorkoutService.Workout getById(long id) {
            BodyForgeClient.WorkoutService.getByIdRequest inValue = new BodyForgeClient.WorkoutService.getByIdRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.getByIdRequestBody();
            inValue.Body.id = id;
            BodyForgeClient.WorkoutService.getByIdResponse retVal = ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).getById(inValue);
            return retVal.Body.getByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getByIdResponse> BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.getByIdAsync(BodyForgeClient.WorkoutService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getByIdResponse> getByIdAsync(long id) {
            BodyForgeClient.WorkoutService.getByIdRequest inValue = new BodyForgeClient.WorkoutService.getByIdRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.getByIdRequestBody();
            inValue.Body.id = id;
            return ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.WorkoutService.getByUserIdResponse BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.getByUserId(BodyForgeClient.WorkoutService.getByUserIdRequest request) {
            return base.Channel.getByUserId(request);
        }
        
        public BodyForgeClient.WorkoutService.Workout[] getByUserId(long userId) {
            BodyForgeClient.WorkoutService.getByUserIdRequest inValue = new BodyForgeClient.WorkoutService.getByUserIdRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.getByUserIdRequestBody();
            inValue.Body.userId = userId;
            BodyForgeClient.WorkoutService.getByUserIdResponse retVal = ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).getByUserId(inValue);
            return retVal.Body.getByUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getByUserIdResponse> BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.getByUserIdAsync(BodyForgeClient.WorkoutService.getByUserIdRequest request) {
            return base.Channel.getByUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getByUserIdResponse> getByUserIdAsync(long userId) {
            BodyForgeClient.WorkoutService.getByUserIdRequest inValue = new BodyForgeClient.WorkoutService.getByUserIdRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.getByUserIdRequestBody();
            inValue.Body.userId = userId;
            return ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).getByUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.WorkoutService.getTemplatesByUserIdResponse BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.getTemplatesByUserId(BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest request) {
            return base.Channel.getTemplatesByUserId(request);
        }
        
        public BodyForgeClient.WorkoutService.Workout[] getTemplatesByUserId(long userId) {
            BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest inValue = new BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.getTemplatesByUserIdRequestBody();
            inValue.Body.userId = userId;
            BodyForgeClient.WorkoutService.getTemplatesByUserIdResponse retVal = ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).getTemplatesByUserId(inValue);
            return retVal.Body.getTemplatesByUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getTemplatesByUserIdResponse> BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.getTemplatesByUserIdAsync(BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest request) {
            return base.Channel.getTemplatesByUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.getTemplatesByUserIdResponse> getTemplatesByUserIdAsync(long userId) {
            BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest inValue = new BodyForgeClient.WorkoutService.getTemplatesByUserIdRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.getTemplatesByUserIdRequestBody();
            inValue.Body.userId = userId;
            return ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).getTemplatesByUserIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.WorkoutService.addWorkoutResponse BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.addWorkout(BodyForgeClient.WorkoutService.addWorkoutRequest request) {
            return base.Channel.addWorkout(request);
        }
        
        public string addWorkout(BodyForgeClient.WorkoutService.Workout workout) {
            BodyForgeClient.WorkoutService.addWorkoutRequest inValue = new BodyForgeClient.WorkoutService.addWorkoutRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.addWorkoutRequestBody();
            inValue.Body.workout = workout;
            BodyForgeClient.WorkoutService.addWorkoutResponse retVal = ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).addWorkout(inValue);
            return retVal.Body.addWorkoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.addWorkoutResponse> BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.addWorkoutAsync(BodyForgeClient.WorkoutService.addWorkoutRequest request) {
            return base.Channel.addWorkoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.addWorkoutResponse> addWorkoutAsync(BodyForgeClient.WorkoutService.Workout workout) {
            BodyForgeClient.WorkoutService.addWorkoutRequest inValue = new BodyForgeClient.WorkoutService.addWorkoutRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.addWorkoutRequestBody();
            inValue.Body.workout = workout;
            return ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).addWorkoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.WorkoutService.deleteWorkoutResponse BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.deleteWorkout(BodyForgeClient.WorkoutService.deleteWorkoutRequest request) {
            return base.Channel.deleteWorkout(request);
        }
        
        public string deleteWorkout(long id) {
            BodyForgeClient.WorkoutService.deleteWorkoutRequest inValue = new BodyForgeClient.WorkoutService.deleteWorkoutRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.deleteWorkoutRequestBody();
            inValue.Body.id = id;
            BodyForgeClient.WorkoutService.deleteWorkoutResponse retVal = ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).deleteWorkout(inValue);
            return retVal.Body.deleteWorkoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.deleteWorkoutResponse> BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.deleteWorkoutAsync(BodyForgeClient.WorkoutService.deleteWorkoutRequest request) {
            return base.Channel.deleteWorkoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.deleteWorkoutResponse> deleteWorkoutAsync(long id) {
            BodyForgeClient.WorkoutService.deleteWorkoutRequest inValue = new BodyForgeClient.WorkoutService.deleteWorkoutRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.deleteWorkoutRequestBody();
            inValue.Body.id = id;
            return ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).deleteWorkoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.WorkoutService.updateWorkoutResponse BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.updateWorkout(BodyForgeClient.WorkoutService.updateWorkoutRequest request) {
            return base.Channel.updateWorkout(request);
        }
        
        public string updateWorkout(BodyForgeClient.WorkoutService.Workout workout) {
            BodyForgeClient.WorkoutService.updateWorkoutRequest inValue = new BodyForgeClient.WorkoutService.updateWorkoutRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.updateWorkoutRequestBody();
            inValue.Body.workout = workout;
            BodyForgeClient.WorkoutService.updateWorkoutResponse retVal = ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).updateWorkout(inValue);
            return retVal.Body.updateWorkoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.updateWorkoutResponse> BodyForgeClient.WorkoutService.WorkoutWebServiceSoap.updateWorkoutAsync(BodyForgeClient.WorkoutService.updateWorkoutRequest request) {
            return base.Channel.updateWorkoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.WorkoutService.updateWorkoutResponse> updateWorkoutAsync(BodyForgeClient.WorkoutService.Workout workout) {
            BodyForgeClient.WorkoutService.updateWorkoutRequest inValue = new BodyForgeClient.WorkoutService.updateWorkoutRequest();
            inValue.Body = new BodyForgeClient.WorkoutService.updateWorkoutRequestBody();
            inValue.Body.workout = workout;
            return ((BodyForgeClient.WorkoutService.WorkoutWebServiceSoap)(this)).updateWorkoutAsync(inValue);
        }
    }
}
