//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyForgeClient.SessionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        private int repsField;
        
        private float weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        private long id_workoutField;
        
        private long id_exerciseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int reps {
            get {
                return this.repsField;
            }
            set {
                if ((this.repsField.Equals(value) != true)) {
                    this.repsField = value;
                    this.RaisePropertyChanged("reps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long id_workout {
            get {
                return this.id_workoutField;
            }
            set {
                if ((this.id_workoutField.Equals(value) != true)) {
                    this.id_workoutField = value;
                    this.RaisePropertyChanged("id_workout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long id_exercise {
            get {
                return this.id_exerciseField;
            }
            set {
                if ((this.id_exerciseField.Equals(value) != true)) {
                    this.id_exerciseField = value;
                    this.RaisePropertyChanged("id_exercise");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionService.SessionWebServiceSoap")]
    public interface SessionWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        BodyForgeClient.SessionService.getByIdResponse getById(BodyForgeClient.SessionService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.getByIdResponse> getByIdAsync(BodyForgeClient.SessionService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since element name getByWorkoutIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getByWorkoutId", ReplyAction="*")]
        BodyForgeClient.SessionService.getByWorkoutIdResponse getByWorkoutId(BodyForgeClient.SessionService.getByWorkoutIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getByWorkoutId", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.getByWorkoutIdResponse> getByWorkoutIdAsync(BodyForgeClient.SessionService.getByWorkoutIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteById", ReplyAction="*")]
        void deleteById(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteById", ReplyAction="*")]
        System.Threading.Tasks.Task deleteByIdAsync(long id);
        
        // CODEGEN: Generating message contract since element name session from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        BodyForgeClient.SessionService.updateResponse update(BodyForgeClient.SessionService.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.updateResponse> updateAsync(BodyForgeClient.SessionService.updateRequest request);
        
        // CODEGEN: Generating message contract since element name session from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        BodyForgeClient.SessionService.addResponse add(BodyForgeClient.SessionService.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/add", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.addResponse> addAsync(BodyForgeClient.SessionService.addRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getById", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.getByIdRequestBody Body;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(BodyForgeClient.SessionService.getByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public getByIdRequestBody() {
        }
        
        public getByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.getByIdResponseBody Body;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(BodyForgeClient.SessionService.getByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.SessionService.Session getByIdResult;
        
        public getByIdResponseBody() {
        }
        
        public getByIdResponseBody(BodyForgeClient.SessionService.Session getByIdResult) {
            this.getByIdResult = getByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByWorkoutIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByWorkoutId", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.getByWorkoutIdRequestBody Body;
        
        public getByWorkoutIdRequest() {
        }
        
        public getByWorkoutIdRequest(BodyForgeClient.SessionService.getByWorkoutIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByWorkoutIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long workoutId;
        
        public getByWorkoutIdRequestBody() {
        }
        
        public getByWorkoutIdRequestBody(long workoutId) {
            this.workoutId = workoutId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByWorkoutIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByWorkoutIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.getByWorkoutIdResponseBody Body;
        
        public getByWorkoutIdResponse() {
        }
        
        public getByWorkoutIdResponse(BodyForgeClient.SessionService.getByWorkoutIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByWorkoutIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.SessionService.Session[] getByWorkoutIdResult;
        
        public getByWorkoutIdResponseBody() {
        }
        
        public getByWorkoutIdResponseBody(BodyForgeClient.SessionService.Session[] getByWorkoutIdResult) {
            this.getByWorkoutIdResult = getByWorkoutIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(BodyForgeClient.SessionService.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.SessionService.Session session;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(BodyForgeClient.SessionService.Session session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(BodyForgeClient.SessionService.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateResponseBody {
        
        public updateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.addRequestBody Body;
        
        public addRequest() {
        }
        
        public addRequest(BodyForgeClient.SessionService.addRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.SessionService.Session session;
        
        public addRequestBody() {
        }
        
        public addRequestBody(BodyForgeClient.SessionService.Session session) {
            this.session = session;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.SessionService.addResponseBody Body;
        
        public addResponse() {
        }
        
        public addResponse(BodyForgeClient.SessionService.addResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addResponseBody {
        
        public addResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionWebServiceSoapChannel : BodyForgeClient.SessionService.SessionWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionWebServiceSoapClient : System.ServiceModel.ClientBase<BodyForgeClient.SessionService.SessionWebServiceSoap>, BodyForgeClient.SessionService.SessionWebServiceSoap {
        
        public SessionWebServiceSoapClient() {
        }
        
        public SessionWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.SessionService.getByIdResponse BodyForgeClient.SessionService.SessionWebServiceSoap.getById(BodyForgeClient.SessionService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public BodyForgeClient.SessionService.Session getById(long id) {
            BodyForgeClient.SessionService.getByIdRequest inValue = new BodyForgeClient.SessionService.getByIdRequest();
            inValue.Body = new BodyForgeClient.SessionService.getByIdRequestBody();
            inValue.Body.id = id;
            BodyForgeClient.SessionService.getByIdResponse retVal = ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).getById(inValue);
            return retVal.Body.getByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.getByIdResponse> BodyForgeClient.SessionService.SessionWebServiceSoap.getByIdAsync(BodyForgeClient.SessionService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.SessionService.getByIdResponse> getByIdAsync(long id) {
            BodyForgeClient.SessionService.getByIdRequest inValue = new BodyForgeClient.SessionService.getByIdRequest();
            inValue.Body = new BodyForgeClient.SessionService.getByIdRequestBody();
            inValue.Body.id = id;
            return ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.SessionService.getByWorkoutIdResponse BodyForgeClient.SessionService.SessionWebServiceSoap.getByWorkoutId(BodyForgeClient.SessionService.getByWorkoutIdRequest request) {
            return base.Channel.getByWorkoutId(request);
        }
        
        public BodyForgeClient.SessionService.Session[] getByWorkoutId(long workoutId) {
            BodyForgeClient.SessionService.getByWorkoutIdRequest inValue = new BodyForgeClient.SessionService.getByWorkoutIdRequest();
            inValue.Body = new BodyForgeClient.SessionService.getByWorkoutIdRequestBody();
            inValue.Body.workoutId = workoutId;
            BodyForgeClient.SessionService.getByWorkoutIdResponse retVal = ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).getByWorkoutId(inValue);
            return retVal.Body.getByWorkoutIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.getByWorkoutIdResponse> BodyForgeClient.SessionService.SessionWebServiceSoap.getByWorkoutIdAsync(BodyForgeClient.SessionService.getByWorkoutIdRequest request) {
            return base.Channel.getByWorkoutIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.SessionService.getByWorkoutIdResponse> getByWorkoutIdAsync(long workoutId) {
            BodyForgeClient.SessionService.getByWorkoutIdRequest inValue = new BodyForgeClient.SessionService.getByWorkoutIdRequest();
            inValue.Body = new BodyForgeClient.SessionService.getByWorkoutIdRequestBody();
            inValue.Body.workoutId = workoutId;
            return ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).getByWorkoutIdAsync(inValue);
        }
        
        public void deleteById(long id) {
            base.Channel.deleteById(id);
        }
        
        public System.Threading.Tasks.Task deleteByIdAsync(long id) {
            return base.Channel.deleteByIdAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.SessionService.updateResponse BodyForgeClient.SessionService.SessionWebServiceSoap.update(BodyForgeClient.SessionService.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public void update(BodyForgeClient.SessionService.Session session) {
            BodyForgeClient.SessionService.updateRequest inValue = new BodyForgeClient.SessionService.updateRequest();
            inValue.Body = new BodyForgeClient.SessionService.updateRequestBody();
            inValue.Body.session = session;
            BodyForgeClient.SessionService.updateResponse retVal = ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.updateResponse> BodyForgeClient.SessionService.SessionWebServiceSoap.updateAsync(BodyForgeClient.SessionService.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.SessionService.updateResponse> updateAsync(BodyForgeClient.SessionService.Session session) {
            BodyForgeClient.SessionService.updateRequest inValue = new BodyForgeClient.SessionService.updateRequest();
            inValue.Body = new BodyForgeClient.SessionService.updateRequestBody();
            inValue.Body.session = session;
            return ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.SessionService.addResponse BodyForgeClient.SessionService.SessionWebServiceSoap.add(BodyForgeClient.SessionService.addRequest request) {
            return base.Channel.add(request);
        }
        
        public void add(BodyForgeClient.SessionService.Session session) {
            BodyForgeClient.SessionService.addRequest inValue = new BodyForgeClient.SessionService.addRequest();
            inValue.Body = new BodyForgeClient.SessionService.addRequestBody();
            inValue.Body.session = session;
            BodyForgeClient.SessionService.addResponse retVal = ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.SessionService.addResponse> BodyForgeClient.SessionService.SessionWebServiceSoap.addAsync(BodyForgeClient.SessionService.addRequest request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.SessionService.addResponse> addAsync(BodyForgeClient.SessionService.Session session) {
            BodyForgeClient.SessionService.addRequest inValue = new BodyForgeClient.SessionService.addRequest();
            inValue.Body = new BodyForgeClient.SessionService.addRequestBody();
            inValue.Body.session = session;
            return ((BodyForgeClient.SessionService.SessionWebServiceSoap)(this)).addAsync(inValue);
        }
    }
}
