//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyForgeClient.AuthenticationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationService.AuthenticationWebServiceSoap")]
    public interface AuthenticationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        BodyForgeClient.AuthenticationService.loginResponse login(BodyForgeClient.AuthenticationService.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.AuthenticationService.loginResponse> loginAsync(BodyForgeClient.AuthenticationService.loginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.AuthenticationService.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(BodyForgeClient.AuthenticationService.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.AuthenticationService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(BodyForgeClient.AuthenticationService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationWebServiceSoapChannel : BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationWebServiceSoapClient : System.ServiceModel.ClientBase<BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap>, BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap {
        
        public AuthenticationWebServiceSoapClient() {
        }
        
        public AuthenticationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.AuthenticationService.loginResponse BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap.login(BodyForgeClient.AuthenticationService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string username, string password) {
            BodyForgeClient.AuthenticationService.loginRequest inValue = new BodyForgeClient.AuthenticationService.loginRequest();
            inValue.Body = new BodyForgeClient.AuthenticationService.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            BodyForgeClient.AuthenticationService.loginResponse retVal = ((BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.AuthenticationService.loginResponse> BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap.loginAsync(BodyForgeClient.AuthenticationService.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.AuthenticationService.loginResponse> loginAsync(string username, string password) {
            BodyForgeClient.AuthenticationService.loginRequest inValue = new BodyForgeClient.AuthenticationService.loginRequest();
            inValue.Body = new BodyForgeClient.AuthenticationService.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((BodyForgeClient.AuthenticationService.AuthenticationWebServiceSoap)(this)).loginAsync(inValue);
        }
    }
}
