//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyForgeClient.ExerciseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exercise", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Exercise : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExerciseService.ExerciseWebServiceSoap")]
    public interface ExerciseWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        BodyForgeClient.ExerciseService.getByIdResponse getById(BodyForgeClient.ExerciseService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.ExerciseService.getByIdResponse> getByIdAsync(BodyForgeClient.ExerciseService.getByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getById", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.ExerciseService.getByIdRequestBody Body;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(BodyForgeClient.ExerciseService.getByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public getByIdRequestBody() {
        }
        
        public getByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.ExerciseService.getByIdResponseBody Body;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(BodyForgeClient.ExerciseService.getByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.ExerciseService.Exercise getByIdResult;
        
        public getByIdResponseBody() {
        }
        
        public getByIdResponseBody(BodyForgeClient.ExerciseService.Exercise getByIdResult) {
            this.getByIdResult = getByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExerciseWebServiceSoapChannel : BodyForgeClient.ExerciseService.ExerciseWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExerciseWebServiceSoapClient : System.ServiceModel.ClientBase<BodyForgeClient.ExerciseService.ExerciseWebServiceSoap>, BodyForgeClient.ExerciseService.ExerciseWebServiceSoap {
        
        public ExerciseWebServiceSoapClient() {
        }
        
        public ExerciseWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExerciseWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExerciseWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExerciseWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.ExerciseService.getByIdResponse BodyForgeClient.ExerciseService.ExerciseWebServiceSoap.getById(BodyForgeClient.ExerciseService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public BodyForgeClient.ExerciseService.Exercise getById(long id) {
            BodyForgeClient.ExerciseService.getByIdRequest inValue = new BodyForgeClient.ExerciseService.getByIdRequest();
            inValue.Body = new BodyForgeClient.ExerciseService.getByIdRequestBody();
            inValue.Body.id = id;
            BodyForgeClient.ExerciseService.getByIdResponse retVal = ((BodyForgeClient.ExerciseService.ExerciseWebServiceSoap)(this)).getById(inValue);
            return retVal.Body.getByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.ExerciseService.getByIdResponse> BodyForgeClient.ExerciseService.ExerciseWebServiceSoap.getByIdAsync(BodyForgeClient.ExerciseService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.ExerciseService.getByIdResponse> getByIdAsync(long id) {
            BodyForgeClient.ExerciseService.getByIdRequest inValue = new BodyForgeClient.ExerciseService.getByIdRequest();
            inValue.Body = new BodyForgeClient.ExerciseService.getByIdRequestBody();
            inValue.Body.id = id;
            return ((BodyForgeClient.ExerciseService.ExerciseWebServiceSoap)(this)).getByIdAsync(inValue);
        }
    }
}
