//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyForgeClient.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        BodyForgeClient.UserService.getByIdResponse getById(BodyForgeClient.UserService.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getById", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.UserService.getByIdResponse> getByIdAsync(BodyForgeClient.UserService.getByIdRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getByUsername", ReplyAction="*")]
        BodyForgeClient.UserService.getByUsernameResponse getByUsername(BodyForgeClient.UserService.getByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.UserService.getByUsernameResponse> getByUsernameAsync(BodyForgeClient.UserService.getByUsernameRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        BodyForgeClient.UserService.addUserResponse addUser(BodyForgeClient.UserService.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<BodyForgeClient.UserService.addUserResponse> addUserAsync(BodyForgeClient.UserService.addUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getById", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.UserService.getByIdRequestBody Body;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(BodyForgeClient.UserService.getByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public getByIdRequestBody() {
        }
        
        public getByIdRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.UserService.getByIdResponseBody Body;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(BodyForgeClient.UserService.getByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.UserService.Users getByIdResult;
        
        public getByIdResponseBody() {
        }
        
        public getByIdResponseBody(BodyForgeClient.UserService.Users getByIdResult) {
            this.getByIdResult = getByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByUsername", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.UserService.getByUsernameRequestBody Body;
        
        public getByUsernameRequest() {
        }
        
        public getByUsernameRequest(BodyForgeClient.UserService.getByUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getByUsernameRequestBody() {
        }
        
        public getByUsernameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.UserService.getByUsernameResponseBody Body;
        
        public getByUsernameResponse() {
        }
        
        public getByUsernameResponse(BodyForgeClient.UserService.getByUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.UserService.Users getByUsernameResult;
        
        public getByUsernameResponseBody() {
        }
        
        public getByUsernameResponseBody(BodyForgeClient.UserService.Users getByUsernameResult) {
            this.getByUsernameResult = getByUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.UserService.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(BodyForgeClient.UserService.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BodyForgeClient.UserService.Users user;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(BodyForgeClient.UserService.Users user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public BodyForgeClient.UserService.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(BodyForgeClient.UserService.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addUserResult;
        
        public addUserResponseBody() {
        }
        
        public addUserResponseBody(bool addUserResult) {
            this.addUserResult = addUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : BodyForgeClient.UserService.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<BodyForgeClient.UserService.UserWebServiceSoap>, BodyForgeClient.UserService.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.UserService.getByIdResponse BodyForgeClient.UserService.UserWebServiceSoap.getById(BodyForgeClient.UserService.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public BodyForgeClient.UserService.Users getById(long id) {
            BodyForgeClient.UserService.getByIdRequest inValue = new BodyForgeClient.UserService.getByIdRequest();
            inValue.Body = new BodyForgeClient.UserService.getByIdRequestBody();
            inValue.Body.id = id;
            BodyForgeClient.UserService.getByIdResponse retVal = ((BodyForgeClient.UserService.UserWebServiceSoap)(this)).getById(inValue);
            return retVal.Body.getByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.UserService.getByIdResponse> BodyForgeClient.UserService.UserWebServiceSoap.getByIdAsync(BodyForgeClient.UserService.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.UserService.getByIdResponse> getByIdAsync(long id) {
            BodyForgeClient.UserService.getByIdRequest inValue = new BodyForgeClient.UserService.getByIdRequest();
            inValue.Body = new BodyForgeClient.UserService.getByIdRequestBody();
            inValue.Body.id = id;
            return ((BodyForgeClient.UserService.UserWebServiceSoap)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.UserService.getByUsernameResponse BodyForgeClient.UserService.UserWebServiceSoap.getByUsername(BodyForgeClient.UserService.getByUsernameRequest request) {
            return base.Channel.getByUsername(request);
        }
        
        public BodyForgeClient.UserService.Users getByUsername(string username) {
            BodyForgeClient.UserService.getByUsernameRequest inValue = new BodyForgeClient.UserService.getByUsernameRequest();
            inValue.Body = new BodyForgeClient.UserService.getByUsernameRequestBody();
            inValue.Body.username = username;
            BodyForgeClient.UserService.getByUsernameResponse retVal = ((BodyForgeClient.UserService.UserWebServiceSoap)(this)).getByUsername(inValue);
            return retVal.Body.getByUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.UserService.getByUsernameResponse> BodyForgeClient.UserService.UserWebServiceSoap.getByUsernameAsync(BodyForgeClient.UserService.getByUsernameRequest request) {
            return base.Channel.getByUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.UserService.getByUsernameResponse> getByUsernameAsync(string username) {
            BodyForgeClient.UserService.getByUsernameRequest inValue = new BodyForgeClient.UserService.getByUsernameRequest();
            inValue.Body = new BodyForgeClient.UserService.getByUsernameRequestBody();
            inValue.Body.username = username;
            return ((BodyForgeClient.UserService.UserWebServiceSoap)(this)).getByUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BodyForgeClient.UserService.addUserResponse BodyForgeClient.UserService.UserWebServiceSoap.addUser(BodyForgeClient.UserService.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public bool addUser(BodyForgeClient.UserService.Users user) {
            BodyForgeClient.UserService.addUserRequest inValue = new BodyForgeClient.UserService.addUserRequest();
            inValue.Body = new BodyForgeClient.UserService.addUserRequestBody();
            inValue.Body.user = user;
            BodyForgeClient.UserService.addUserResponse retVal = ((BodyForgeClient.UserService.UserWebServiceSoap)(this)).addUser(inValue);
            return retVal.Body.addUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BodyForgeClient.UserService.addUserResponse> BodyForgeClient.UserService.UserWebServiceSoap.addUserAsync(BodyForgeClient.UserService.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<BodyForgeClient.UserService.addUserResponse> addUserAsync(BodyForgeClient.UserService.Users user) {
            BodyForgeClient.UserService.addUserRequest inValue = new BodyForgeClient.UserService.addUserRequest();
            inValue.Body = new BodyForgeClient.UserService.addUserRequestBody();
            inValue.Body.user = user;
            return ((BodyForgeClient.UserService.UserWebServiceSoap)(this)).addUserAsync(inValue);
        }
    }
}
